export const SENTENCES: string[] = [
    "Summer sunsets paint the sky in brilliant hues.",
    "A gentle breeze carries the scent of flowers.",
    "Children laugh as they run through the park.",
    "Morning coffee tastes best with a friend.",
    "Raindrops dance on the windowpane at night.",
    "Freshly baked bread warms the whole kitchen.",
    "A curious cat explores every hidden corner.",
    "Bright balloons floated across the carnival.",
    "Old books hold stories waiting to be told.",
    "Soft music drifts through the cozy café.",
    "The ocean waves whispered secrets to the shore.",
    "Golden leaves drift down from tall trees.",
    "A single candle lit the darkened room.",
    "Hot chocolate tastes sweetness in winter’s chill.",
    "Starry skies make the world feel endless.",
    "Tiny footsteps tiptoed across the wooden floor.",
    "Fresh paint gave the room a new beginning.",
    "Snowflakes swirl gently in the crisp air.",
    "A friendly dog wagged its tail on the path.",
    "Colorful kites soared high on windy days.",
    "Soft pillows made the perfect reading nook.",
    "The bakery window displayed delicious treats.",
    "Tiny seeds sprouted into green, leafy sprouts.",
    "Bright lanterns lit up the festive street.",
    "A gentle rain cooled the summer afternoon.",
    "Fresh strawberries smelled sweet in the sun.",
    "A child’s giggle echoed down the hallway.",
    "Warm sunlight streamed through the curtains.",
    "The garden woke up with chirping birds.",
    "Fresh dew sparkled on every blade of grass."
];
